Drive v3 file snippet
googleworkspace/node-samples pull request #173
Opened 2022-05-13 16:56 UTC by RajeshGogo

# Description
Drive-v3 file_snippets
export_pdf(Bug_id-232039687) : Download a document file in Pdf format.
move_file_to_folder(Bug_id-232040050) : Move one file to specified folder.
search_file(Bug_id-232177275) : Search a file in drive location
share_file(Bug_id-232177364) : Batch permission modification
upload_basic(Bug_id-232177235) : Insert a new file
touch_file(Bug_id-232177411) : Change file's modification timestamp

## Has it been tested?
- [X] Development testing done
- [ ] Unit or integration test implemented

## Checklist
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have performed a peer-reviewed with team member(s)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] Any dependent changes have been merged and published in downstream modules

2022-05-16 23:51 UTC, sqrrrl requested changes

2022-05-16 23:51 UTC, sqrrrl commented on drive/snippets/drive_v3/file_snippets/export_pdf.js
> +  // Get credentials and build service
Move closer to statements so it reads better. Feels a little disconnected with the require statements in between

2022-05-16 23:51 UTC, sqrrrl commented on drive/snippets/drive_v3/file_snippets/export_pdf.js
> +  fileId = realFileId;
fileId is undefined. Delete the assignment and just rename realFileId -> fileId.

See comments on #174 for additional details.

2022-05-16 23:51 UTC, sqrrrl commented on drive/snippets/drive_v3/file_snippets/move_file_to_folder.js
> +async function moveFileToFolder(realFileId, realFolderId) {
Same comments as export_pdf -- align the auth comments & remove the fileId/folderId reassignments

2022-05-16 23:51 UTC, sqrrrl commented on drive/snippets/drive_v3/file_snippets/search_file.js
> +  // Get credentials and build service
Same as other files

2022-05-16 23:51 UTC, sqrrrl commented on drive/snippets/drive_v3/file_snippets/search_file.js
> +  const pageToken = null;
Not actually using page token here. Either don't page or add an outer loop to do paging:

```
let pageToken = null;
do {
  const res = await ....
  res.data.files.forEach(...);
  pageToken = res.data.nextPageToken;
} while (pageToken);
```

2022-05-16 23:51 UTC, sqrrrl commented on drive/snippets/drive_v3/file_snippets/share_file.js
> +  // Get credentials and build service
Same comments as other files re: auth comments & reassignments

2022-05-16 23:51 UTC, sqrrrl commented on drive/snippets/drive_v3/file_snippets/share_file.js
> +    async.eachSeries(permissions, function(permission) {
Was going to suggest using batch requests, but looks like the nodejs client doesn't support it :(

2022-05-16 23:51 UTC, sqrrrl commented on drive/snippets/drive_v3/file_snippets/share_file.js
> +          .then(function(result) {
Indentation seems off. Reformat

2022-05-16 23:51 UTC, sqrrrl commented on drive/snippets/drive_v3/file_snippets/touch_file.js
> +async function touchFile(realFileId, realTimestamp) {
Same comments as other files

2022-05-16 23:51 UTC, sqrrrl commented on drive/snippets/drive_v3/file_snippets/upload_basic.js
> +  // Get credentials and build service
Same comments as other files

2022-05-17 06:36 UTC, anuraggoogler commented
Done

2022-05-25 22:53 UTC, merged