Drive v3 appdata Upload_to_folder & Upload_with_conversion
googleworkspace/node-samples pull request #174
Opened 2022-05-13 17:00 UTC by RajeshGogo

# Description
Drive-v3 file_snippet
Upload_to_folder(Bug_id-232177413) : Upload file with conversion.
Upload_with_conversion(Bug_id-232177413) : Upload a file to the specified folder.

## Has it been tested?
- [X] Development testing done
- [ ] Unit or integration test implemented

## Checklist
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have performed a peer-reviewed with team member(s)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] Any dependent changes have been merged and published in downstream modules

2022-05-16 23:11 UTC, sqrrrl requested changes

2022-05-16 23:11 UTC, sqrrrl commented on drive/snippets/drive_v3/file_snippets/upload_to_folder.js
> +  // Get credentials and build service
Move these closer to the actual statements. Currently seems a little disconnected with the require statements in between.

2022-05-16 23:11 UTC, sqrrrl commented on drive/snippets/drive_v3/file_snippets/upload_to_folder.js
> +  folderId = realFolderId;
folderId is undefined. Also can likely be eliminated and just rename the parameter realFolderId to folderId.

The original intent was to be able to include a line that initialized folderId to a constant illustrative value so users know what IDs looks like. But that can be accomplished through other means -- a default value in the params, or just a comment like:

```
async function uploadToFolder(folderId) {
  // TODO(developer): Set folder ID
  // folderId = '0Bz2X2-r-Ou9ffjVzUFREZ09PdjVaZWJLYTBWdXZWaUR0YndVZXQtOEtlb3p2Q1d6UDJyRF';
  ....
 ```

2022-05-16 23:11 UTC, sqrrrl commented on drive/snippets/drive_v3/file_snippets/upload_with_conversion.js
> +  // Get credentials and build service
Same as other file

2022-05-17 06:37 UTC, anuraggoogler commented
Done

2022-05-25 21:24 UTC, merged